apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    app: django-app
spec:
  selector:
    app: django-app
  type: LoadBalancer  # Use LoadBalancer to expose externally; for internal use, change to ClusterIP
  ports:
    - protocol: TCP
      port: 80       # The port exposed by the service
      targetPort: 8080  # The port where the Django app is running inside the container
